## importing relevant libraries

In [1]:
import numpy as np

### Declaring scalar

In [2]:
x = 5
x

5

### Vector

In [3]:
v = np.array([5,-2,4])

In [5]:
v
#default v is row vector

array([ 5, -2,  4])

### Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [8]:
type(x)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
x_array = np.array(5)
x_array

array(5)

In [12]:
type(x_array)

numpy.ndarray

### Data shapes

In [15]:
m.shape

(2, 3)

In [16]:
v.shape

(3,)

In [17]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [18]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [19]:
x_array.shape

()

### Tensor

In [20]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [21]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [22]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [23]:
t.shape

(2, 2, 3)

### Manually creating tensor

In [24]:
t_mannual = np.array([[[ 5, 12,  6],[-3,  0, 14]],[[9,8,7],[1,3,-5]]])
t_mannual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Operations on matrices 

### Addition and subtraction 

In [25]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [26]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [27]:
m1 + 5

array([[10, 17, 11],
       [ 2,  5, 19]])

### Transpose of matrix

In [28]:
m1.transpose()

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [30]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [31]:
m2.T

array([[ 9,  1],
       [ 8,  3],
       [ 7, -5]])

### Dot product

In [35]:
x = np.array([5,12,6])
y = np.array([1,2,3])
np.dot(x,y)

47

In [36]:
np.dot(x,5)

array([25, 60, 30])

In [37]:
5*x

array([25, 60, 30])

In [38]:
3*m2

array([[ 27,  24,  21],
       [  3,   9, -15]])

In [39]:
np.dot(m1.T,m2)

array([[ 42,  31,  50],
       [108,  96,  84],
       [ 68,  90, -28]])